### ISSUE TITLE
Is it possible to implement a language changer?

### ISSUE THREAD

**Issue by HydraLM81** [ChaozhongLiu/DyberPet#1]
I tried by going through the Python files and changing the text to English in all the files in the subfolder DyberPet ([here](https://github.com/HydraLM81/random-code/tree/main/DyberPet)), but I never got it to compile and run correctly, so I figured I'd ask the creator. Thanks!

**Comment by ChaozhongLiu** [comment]
> I tried by going through the Python files and changing the text to English in all the files in the subfolder DyberPet ([here](https://github.com/HydraLM81/random-code/tree/main/DyberPet)), but I never got it to compile and run correctly, so I figured I'd ask the creator. Thanks!

Here there, thanks for trying this DyberPet framework!
For sure! language changer whould be a great enhancement for users and developers from all over the world! I will add it to my to-do list.

Meanwhile, if you do wanna have your own Pet created, please let me know here what problem you met when running it!
I will be here to help! xD

BTW, I should really add English documents in this repository but just being too lazy all the time. I will do it ASAP!

**Comment by ChaozhongLiu** [comment]
Hi there, sorry for the delay.
I recently published the frame and received many bug and issue report from users. I'm currently focusing on bugs and high-priority enhancement, will let you know when the language changer finished! Thx!

**Comment by ChaozhongLiu** [comment]
The language changer is now released, with UI reconstructed. I haven't finished the translation of some part of the UI, but it's there. It has been a long time though 🤣 Not sure if you still need it.

**Comment by HydraLM81** [comment]
Fantastic, thanks!
