### ISSUE TITLE
在windows下运行0.3.1的exe报错

### ISSUE THREAD

**Issue by ZWzheng96** [ChaozhongLiu/DyberPet#14]
如图
试过同样环境0.3.0直接双击exe可以正常打开
![image](https://github.com/ChaozhongLiu/DyberPet/assets/136017555/c1846b64-9e76-439f-a83e-32abd865afa3)
另外在conda里面配置环境克隆仓库运行py脚本时获得了这样的提示
![image](https://github.com/ChaozhongLiu/DyberPet/assets/136017555/162be727-5ea0-48a6-b7e5-fdb16787490a)
请帮忙看看是什么问题

**Comment by ChaozhongLiu** [comment]
第一个问题是win32 dll 的问题，我尝试在本地解决了这个问题，然后在自己的PC上运行没有问题，但看起来并没有成功解决。
第二个问题是bug，感谢你的反馈，马上就会改过来

**Comment by ChaozhongLiu** [comment]
第二个问题代码已修改，可以试一下～

**Comment by ZWzheng96** [comment]
辛苦了！刚刚尝试了，conda环境可以运行了~

**Comment by ChaozhongLiu** [comment]
@ZWzheng96 能否麻烦你尝试一下最新的 [release](https://github.com/ChaozhongLiu/DyberPet/releases/tag/v0.3.1b)，不知道 DLL 缺失的问题是否能够解决。谢谢！

**Comment by ZWzheng96** [comment]
![image](https://github.com/ChaozhongLiu/DyberPet/assets/136017555/2355753e-f90f-43f0-ab9e-df2d58b980bb)
好像还是不行😂

**Comment by ChaozhongLiu** [comment]
@ZWzheng96 这次暴力把缺失的全塞进去了，找了大佬帮忙测试。已经在 [release](https://github.com/ChaozhongLiu/DyberPet/releases/tag/v0.3.1b) 里面更新，麻烦你再试一试了 🤣

**Comment by ZWzheng96** [comment]
现在可以直接运行😂辛苦了

**Comment by ChaozhongLiu** [comment]
感谢你哈！
