### ISSUE TITLE
在windows下运行0.3.1的exe报错

### ISSUE THREAD

**Issue by hanxingshuo** [ChaozhongLiu/DyberPet#16]
运行0.3.1的exe
![image](https://github.com/ChaozhongLiu/DyberPet/assets/123861872/e714a822-2796-4cb0-990c-74c0ef91077e)
出错

**Comment by ChaozhongLiu** [comment]
请参考 #14 
已经解决

**Comment by hanxingshuo** [comment]
> 请参考 #14
