### ISSUE TITLE
python版本过高会报错

### ISSUE THREAD

**Issue by Cirno-NULL** [ChaozhongLiu/DyberPet#2]
# 环境：
系统：win10
python版本：3.11，3.9
![image](https://user-images.githubusercontent.com/41545185/215307070-bec6ed4c-f446-4af0-9e3c-99cd9c0910d8.png)

# 运行结果：
## 3.11报错
![image](https://user-images.githubusercontent.com/41545185/215306940-5f7845e9-c0c6-4fc7-b1f0-7a7ee6f6156c.png)

## 3.9正常
![image](https://user-images.githubusercontent.com/41545185/215306884-96bfbe22-051d-4ed0-8301-37e08d9d638b.png)

**Comment by ChaozhongLiu** [comment]
能否提供一下在3.11和3.9环境里pyqt5的版本？看起来似乎新版本不会自动把float变成int了？只有这一个问题还好说，有其他的问题我可能要确定一下各个package的版本问题了。谢谢你！

**Comment by Cirno-NULL** [comment]
![image](https://user-images.githubusercontent.com/41545185/215308595-88edb544-7261-4a74-a8c1-f99e69b8105e.png)

**Comment by ChaozhongLiu** [comment]
谢谢你！我明天起床会更新一版修改这个报错的~ 到时候如果3.11还是不能运行，再... 再说 hhhhh

**Comment by ChaozhongLiu** [comment]
更改了所有可能出现 float 和 int 不一致的地方，有问题随时告诉我~
