### ISSUE TITLE
宠物不会掉下去BUG

### ISSUE THREAD

**Issue by zstthm** [ChaozhongLiu/DyberPet#24]
将宠物用鼠标拖拽，然后快去向桌面顶部丢弃，然后就卡上面了。
![image](https://github.com/ChaozhongLiu/DyberPet/assets/61346687/06040884-c693-421a-8d6e-ea2c78d378af)

**Comment by zstthm** [comment]
补充一点 向上拽者丢时候，鼠标碰到顶部边框

**Comment by ChaozhongLiu** [comment]
收到，应该是和指针坐标&速度判定有关的 bug
感谢！

**Comment by ChaozhongLiu** [comment]
已经在最新的 commit 更正
