### ISSUE TITLE
关于系统设置内设置项在应用程序重启后失效的反馈

### ISSUE THREAD

**Issue by yuanbenxin** [ChaozhongLiu/DyberPet#25]
宠物设置中关闭“允许掉落”后虽然可以生效，但**在程序重启后又会恢复到开启状态**，实测其它设置项并无此问题，但是**每次重新进入程序之后都要再关闭一下这个设置**，所以请修复一下这个bug，因为个人并不喜欢“允许掉落”功能，这样每次都得手动关闭又很繁琐，难道设置不能自动保存吗？

**Comment by ChaozhongLiu** [comment]
这不是bug，是我根本没把它加到设置项里，近期更新就加进去

**Comment by ChaozhongLiu** [comment]
已经在刚刚的 [commit](https://github.com/ChaozhongLiu/DyberPet/commit/11f09700ee35ee4564f1fc3c70fbb4ca1bebf55b) 添加了这个功能。
但我不能因为一个小的功能改动就更新版本 Release，如果你急着要，去 [run_DyberPet.py](https://github.com/ChaozhongLiu/DyberPet/blob/main/run_DyberPet.py#L33) 看看怎么自己打包
