### ISSUE TITLE
字体显示问题

### ISSUE THREAD

**Issue by tnt0829** [ChaozhongLiu/DyberPet#26]
![Screenshot 2024-07-20 1721092](https://github.com/user-attachments/assets/e9a962f0-6079-4150-a120-17160c255973)
不知道是我的问题还是怎么的

**Comment by ChaozhongLiu** [comment]
这个确实是系统解压缩的问题，你的 res/role/里面的文件夹名字应该也是乱码，这个问题和桌宠没关系哈
把 ``res/role/乱码文件夹名字`` 改成 ```像素猫meme`` 就好了~

**Comment by ChaozhongLiu** [comment]
如果没什么问题的话，我就关闭 Issue 了哈
