### ISSUE TITLE
物品为0后仍然滞留背包，且可被消费，使物品数量为负数

### ISSUE THREAD

**Issue by MomentDerek** [ChaozhongLiu/DyberPet#28]
![image](https://github.com/user-attachments/assets/2a67dc87-7b8f-4aeb-9940-d629880f5963)
![image](https://github.com/user-attachments/assets/069a54b7-1808-4ace-8490-67e85506fde6)

重启后物品持续为负数，但背包内不再显示

**Comment by MomentDerek** [comment]
这个bug的复现大致如下：
在宠物还在吃的时候喂下一个食品，然后这个食品就会卡住，无法消费，此时这个食品为选中的状态
然后去商店里把这个食品卖掉，再回到背包，发现这个食品还在，且还是无法消费
然后将这个食品取消选中，去到其他页面（比如商店）后再回来，发现这个食品能一直被消费，数量突破0，可以一直负数

**Comment by MomentDerek** [comment]
这个食品可能得是只能增加饱腹感的食品才会触发

**Comment by ChaozhongLiu** [comment]
谢谢你的反馈！ 上个星期这个 bug 在源代码里已经修复了，因为不是致命的影响所以没有发布新的 release

**Comment by 4F554E504F1F** [comment]
发现新的触发此bug的方式，在任意状态下从商店售卖物品至零物品，此时背包物品不会消失任然能使用而且使用后不会消耗。并且此后背包和商店的物品数量不同步。

**Comment by ChaozhongLiu** [comment]
> 发现新的触发此bug的方式，在任意状态下从商店售卖物品至零物品，此时背包物品不会消失任然能使用而且使用后不会消耗。并且此后背包和商店的物品数量不同步。

谢谢你的反馈，这个上个星期也已经修复了
