### ISSUE TITLE
开发文档错误

### ISSUE THREAD

**Issue by yuchenwei28** [ChaozhongLiu/DyberPet#29]
art_dev.md中“”“# 除了这些常规动作，还有4个内部使用的特殊动作名称
    # 请不要占用这些名称，这些动画也不会在动作列表中显示
    # 可以注意到，这些动作的 act_type 是 [0, 100000]，我用此来表示这个是特殊动作
    # feed_1,2,3 是吃到不同喜好食物后的反应，定义 "sound" 还可以播放语音 (语音在后面的通知个性化部分讲解)
    # on_floor 是角色落地瞬间的落地动作

    {"name":"feed_1", "act_list":["feed_1"], "act_prob":0, "act_type":[0,10000], "sound":["feed_1"]},
    {"name":"feed_2", "act_list":["feed_2"], "act_prob":0, "act_type":[0,10000], "sound":["feed_2"]},
    {"name":"feed_3", "act_list":["feed_3"], "act_prob":0, "act_type":[0,10000], "sound":["feed_3"]},
    {"name":"on_floor", "act_list":["on_floor"], "act_prob":0, "act_type":[0,10000]}
  ]”“”部分里，注释写了100000代码写了10000，

**Comment by ChaozhongLiu** [comment]
其实没有影响啦，只是随便写了一个很大的数值，写 100 其实都行
