### ISSUE TITLE
特殊条件可导致闪退/报错

### ISSUE THREAD

**Issue by Cirno-NULL** [ChaozhongLiu/DyberPet#3]
# 环境：
python版本：3.9

# 前置条件：
* 食谱fv_lock全部大于0
  宠物FV_lvl等于0

即sum(all_probs)等于0时

# 步骤：
一直点宠物直到触发食品掉落

# 结果：
满足前置条件的情况下触发食品掉落会导致报错
![image](https://user-images.githubusercontent.com/41545185/215314869-d7ea1e33-4f36-4d47-8170-fd2a31860a90.png)

**Comment by Cirno-NULL** [comment]
刚刚加了几行代码在定位bug
现在图片里报错的行数和github上的保持一致了
本质上就是权重和为零导致的报错
（这个是github上默认的物品列表权重）

**Comment by ChaozhongLiu** [comment]
而你，我的朋友，你才是真正的英雄。马上改！

**Comment by ChaozhongLiu** [comment]
已经解决了这种错误的发生，还存在问题请告诉我~
