### ISSUE TITLE
bug:左击拖动进入动画后不松开直接点击右键弹出菜单框后，猫咪动画不恢复

### ISSUE THREAD

**Issue by zjclxx** [ChaozhongLiu/DyberPet#35]
操作：
左击拖动进入动画后不松开直接点击右键弹出菜单框后

现象：
猫咪动画不恢复，再次左击后恢复动画

https://github.com/user-attachments/assets/a2d7c6b7-cde9-4938-9e4e-a7529cf9687e

期望：
状态能恢复

**Comment by ChaozhongLiu** [comment]
感谢你的反馈，我研究一下，争取下个版本前解决

**Comment by zjclxx** [comment]
> 感谢你的反馈，我研究一下，争取下个版本前解决
👍

**Comment by ChaozhongLiu** [comment]
刚刚修复了，直接禁用了左键拖拽时的右键活动
