### ISSUE TITLE
程序跨日期一直启动的情况下 喂养天数不会更新

### ISSUE THREAD

**Issue by linger7710** [ChaozhongLiu/DyberPet#37]
![87f863120bfc65fe520b665c682d152](https://github.com/user-attachments/assets/00f52aef-2408-45ad-ab92-54e09bf7758f)

**Comment by ChaozhongLiu** [comment]
麻烦你进入 data 文件夹 把 pet_data.json 的内容复制到这里来

**Comment by linger7710** [comment]
{
    "像素猫meme": {
        "HP": 169,
        "HP_tier": 3,
        "FV": 88,
        "FV_lvl": 3,
        "items": {
            "苹果": 0,
            "骨头": 0,
            "牛奶": 0,
            "山竹": 0,
            "小鱼干": 0,
            "番茄炒蛋": 0,
            "皮克啾": 1,
            "馄饨": 0,
            "小炒肉": 0,
            "酸奶": 0,
            "黄瓜": 0,
            "绿舌头": 0,
            "芝士汉堡": 4,
            "猫粮": 12,
            "香蕉": 0
        },
        "coins": 4700,
        "days": 1,
        "last_opened": "2024-8-16"
    }
}

**Comment by ChaozhongLiu** [comment]
现在关闭再打开一次呢？

**Comment by ChaozhongLiu** [comment]
我去玩黑猴了 可能不能及时回复哈

**Comment by linger7710** [comment]
羡慕啊哈哈 退出再打开就可以了 可能是一直没关机的原因

**Comment by ChaozhongLiu** [comment]
我懂了 感谢你反馈 我确实没考虑跨天的时候程序还开着
下个版本改过来！

**Comment by ChaozhongLiu** [comment]
源代码已经改过来了，这两天应该就会发布新版本~
