### ISSUE TITLE
人物的网盘链接失效了

### ISSUE THREAD

**Issue by JoeXuan123** [ChaozhongLiu/DyberPet#39]
麻烦解决一下，谢谢
![image](https://github.com/user-attachments/assets/01a87eb6-d456-488e-84f1-8bb84ac01548)

**Comment by ChaozhongLiu** [comment]
链接: https://pan.baidu.com/s/1VCqQLucCbLGertCFsAFJnA?pwd=6agc 提取码: 6agc 
下次这个问题私信我哈 这个页面是给程序问题的~

**Comment by ChaozhongLiu** [comment]
文档里的链接也更新了~

**Comment by JoeXuan123** [comment]
好的谢谢啦
