### ISSUE TITLE
60eb1e3版本缺少./data/pets.json

### ISSUE THREAD

**Issue by Cirno-NULL** [ChaozhongLiu/DyberPet#4]
![image](https://user-images.githubusercontent.com/41545185/215318671-b0d98c2a-4df8-408d-a330-6773e2fb2b9d.png)
![image](https://user-images.githubusercontent.com/41545185/215318574-cfdc5cf3-a42b-45a2-8801-d2ead51cacfb.png)

**Comment by ChaozhongLiu** [comment]
这个是后来改了文件结构~ pets.json放到别的地方去了~新版本往后都不会在``data/``下面了。我先不关Issue，你有啥需求跟我说哈

**Comment by ChaozhongLiu** [comment]
人傻了 两头更新混乱了，一会更新一版就改过来~ 你自己用的话可以先改到``res/role/pets.json``

**Comment by ChaozhongLiu** [comment]
第117次commit把代码修改过来了~
