### ISSUE TITLE
宠物点击几下就消失了

### ISSUE THREAD

**Issue by AlexAnorak** [ChaozhongLiu/DyberPet#42]
看了一下命令行,估计就是这个问题
QPixmap::scaled: Pixmap is a null pixmap

**Comment by ChaozhongLiu** [comment]
麻烦你提供完整的终端日志，可以录视频然后截图
单给我这一句没办法debug

**Comment by ChaozhongLiu** [comment]
直接把视频发上来也行～

**Comment by AlexAnorak** [comment]
https://github.com/user-attachments/assets/34323d7d-623a-4ecb-abae-183d8176e3cf

不好意思,没有找到日志在哪,所以录了个视频

**Comment by AlexAnorak** [comment]
是Windows,那只是个桌面美化

**Comment by ChaozhongLiu** [comment]
那有没有试过关掉美化软件再打开？
我视频一帧一帧看也没有找到报错，应该不是软件问题

**Comment by AlexAnorak** [comment]
似乎确实没有问题了,因为这个美化软件有控制置顶显示,然后我这也出现了 #36 ,我感觉可以也是这个问题

**Comment by ChaozhongLiu** [comment]
好的，那我就关闭这个 Issue 了。#36 我还在研究

**Comment by AlexAnorak** [comment]
诶我不是很理解为什么消失后alt tab上也看不到啊

**Comment by ChaozhongLiu** [comment]
这是因为窗口属性的设置
