### ISSUE TITLE
有办法可以自定义提醒声音吗

### ISSUE THREAD

**Issue by Eons-Adrift** [ChaozhongLiu/DyberPet#44]
试着改了下音频文件，然后就不出所料的失败了☹️

**Comment by ChaozhongLiu** [comment]
有 [开发文档](https://github.com/ChaozhongLiu/DyberPet/blob/main/docs/art_dev.md#%E4%B8%AA%E6%80%A7%E5%8C%96%E9%80%9A%E7%9F%A5%E7%B3%BB%E7%BB%9F) 里面有写
