### ISSUE TITLE
長這樣怎麼解決？

### ISSUE THREAD

**Issue by TokoyamiShuu** [ChaozhongLiu/DyberPet#52]
![螢幕擷取畫面 2024-11-25 091304](https://github.com/user-attachments/assets/c22cec1d-ede7-47b4-8a6b-3d713762253b)

**Comment by ChaozhongLiu** [comment]
@TokoyamiShuu 可以截图一下你的 【文档】 文件夹么，里面应该会有一个 DyberPet 的文件夹，如果没有，就创建一个再打开试试

**Comment by ChaozhongLiu** [comment]
太久没有回复了，如果没有问题了我就关闭 Issue 了
