### ISSUE TITLE
extra_windows中的DPDialogue对象怎么调用

### ISSUE THREAD

**Issue by qkr141** [ChaozhongLiu/DyberPet#6]
大佬，我没找到DPDialogue对象有谁调用，想知道该如何调用，求救

**Comment by ChaozhongLiu** [comment]
是代码层面还是在开发素材层面呀？

**Comment by qkr141** [comment]
代码层面，想打开对话窗口

**Comment by ChaozhongLiu** [comment]
[Accessory.py](https://github.com/ChaozhongLiu/DyberPet/blob/main/DyberPet/Accessory.py#L113)里面在调用，是通过使用物品时触发实现的

**Comment by qkr141** [comment]
奥奥，这个acc_dict里面存的是道具是吧，懂了，太感谢了

**Comment by ChaozhongLiu** [comment]
是的 这个变量的创建在[这里](https://github.com/ChaozhongLiu/DyberPet/blob/main/DyberPet/DyberPet.py#L1070)
