### ISSUE TITLE
呆啵宠物使用Windows系统的“任务计划程序”调用启动报错

### ISSUE THREAD

**Issue by zbtls** [ChaozhongLiu/DyberPet#8]
为了方便程序开机自启，我使用“任务计划程序”在用户登录时调用启动程序，但是它报错了：

- Traceback (most recent call last):
-   File "呆啵宠物-原神.py", line 7, in <module>
-   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
-   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
-   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
-   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
-   File "DyberPet\DyberPet.py", line 39, in <module>
-   File "DyberPet\settings.py", line 90, in init
-   File "DyberPet\settings.py", line 171, in get_petlist
- FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'res/role'

任务的“操作”一栏中我选择的类型是“启动程序”，“程序或脚本”一栏中我填写的是“"E:\Program Files\DyberPet_GenshinImpact-main\呆啵宠物-原神.exe"”
请问有什么解决办法吗？建议在设置中加入程序开机自启的选项。

**Comment by ChaozhongLiu** [comment]
开机自启其实已经在做了
我不太确定你这个问题是什么，但我觉得大概率是因为自启时候的working directory不是``E:\Program Files\DyberPet_GenshinImpact-main\``

**Comment by Marcus-P-114514** [comment]
开机自启我完成了，在新Pr里，目前仅限Windows

使用了另外一种方法，目前个人测试过没有出错

**Comment by zbtls** [comment]
哦，谢谢。我认为这个issues可以关了。
另外插句题外话：我们这边的运营商对大部分国外网站进行了屏蔽、限流、DNS污染等措施[https://www.bilibili.com/video/BV1ZD4y1Y7YA/](url)，现在就连上GitHub都要用些手段了（悲）。
希望在国内有镜像源啥的……

**Comment by ChaozhongLiu** [comment]
有时间了会弄镜像的，这段时间在国内我上GitHub也很痛苦 😂
