### ISSUE TITLE
双显示器无法放到副屏幕

### ISSUE THREAD

**Issue by wubo752** [ChaozhongLiu/DyberPet#9]
双显示器无法放到副屏幕吗？我托到副屏自动回到主屏了

**Comment by ChaozhongLiu** [comment]
是最新的code嘛 能否提供一些细节呢？

**Comment by wubo752** [comment]
v0.2.2版，原神版，我想托到第二显示器，拖过去还是会立刻回到主显示器

**Comment by ChaozhongLiu** [comment]
我刚刚测试是没问题的欸
你能提供一些具体信息么，截图一下显示设置就行

**Comment by wubo752** [comment]
那可能是我用平板借助小米妙享当副屏的原因吧

**Comment by ChaozhongLiu** [comment]
估计是的 hhhhh 那我close了哈
